version: '2'
services:
  spdlog-experimentation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_TO_FILE: "true" # causing memory leak
      LOG_TO_CONSOLE: "true"